name: learn-github-actions
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
jobs:

  dev_py_syntax_validation:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v2
      - name: pyflakes
        uses: reviewdog/action-pyflakes@master
        with:
          github_token: ${{ secrets.gh_token }}
          level: error

  upload-to-cloud-storage-action:
    needs: python_syntax_validation
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - id: auth
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.gcp_credentials }}
      - id: upload-file
        uses: google-github-actions/upload-cloud-storage@main
        with:
          path: to_gcs
          destination: data_team_test2

  upload-to-cloud-rsync:
    needs: python_syntax_validation
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - id: show-ls
        run: |
          ls
      - id: set-cloud-sdk
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.gcp_project }}
          service_account_key: ${{ secrets.gcp_credentials }}
          export_default_credentials: true
      - id: use-gcloud-cli
        run: gcloud info
      - id: gsutils-rsync-to-gcs
        run: gsutil rsync to_gcs gs://data_team_test2/rsync_test_ci_to_gcs