name: learn-github-actions
on:
  push:
    branches:
      - main
      - develop 
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: show-ls
        run: | 
          ls

  pyflakes:
    needs: setup
    name: python code validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pyflakes
        uses: reviewdog/action-pyflakes@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check # Change reporter.

  upload-to-cloud-storage-action:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: show-ls
        run: | 
          ls
      - id: upload-file
        uses: google-github-actions/upload-cloud-storage@main
        with:
          credentials: ${{ secrets.gcp_credentials }}
          path: to_gcs
          destination: data_team_test2

  upload-to-cloud-rsync:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: show-ls
        run: | 
          ls
      - id: set-cloud-sdk
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.gcp_project }}
          service_account_key: ${{ secrets.gcp_credentials }}
          export_default_credentials: true
      - id: use-gcloud-cli
        run: gcloud info
      - id: gsutils-rsync-to-gcs
        run: gsutil rsync to_gcs gs://data_team_test2/rsync_test_ci_to_gcs