name: learn-github-actions

on:
  - push
  - pull_request

jobs:
  dev_py_syntax_validation:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v2
      - name: pyflakes
        uses: reviewdog/action-pyflakes@master
  prod_py_syntax_validation:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v2
      - name: pyflakes
        uses: reviewdog/action-pyflakes@master
    
          

  upload-to-cloud-storage-action:
    needs: dev_py_syntax_validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: auth
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.gcp_credentials }}
      - id: upload-file
        uses: google-github-actions/upload-cloud-storage@main
        with:
          path: to_gcs
          destination: data_team_test2

  upload-to-cloud-rsync:
    needs: prod_py_syntax_validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: show-ls
        run: |
          ls
      - id: set-cloud-sdk
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.gcp_project }}
          service_account_key: ${{ secrets.gcp_credentials }}
          export_default_credentials: true
      - id: use-gcloud-cli
        run: gcloud info
      - id: gsutils-rsync-to-gcs
        run: gsutil rsync to_gcs gs://data_team_test2/rsync_test_ci_to_gcs