name: learn-github-actions
on:
  push:
    branches:
      - main
      - develop 
jobs:
  upload-to-cloud-storage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: show-ls
        run: | 
          ls
      - id: upload-file
        uses: google-github-actions/upload-cloud-storage@main
        with:
          credentials: ${{ secrets.gcp_credentials }}
          path: to_gcs
          destination: data_team_test2
